# Generated by Django 4.2.11 on 2024-03-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=34)),
                ('prenom', models.CharField(max_length=34)),
                ('date_enquete', models.DateTimeField(auto_now_add=True)),
                ('condition_eleve', models.CharField(choices=[('CONF', 'CONF'), ('ABAN', 'ABAN'), ('PROP', 'PROP')], max_length=34)),
                ('sex', models.CharField(choices=[('Fille', 'Fille'), ('Garcon', 'Garcon')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('cs_py', models.CharField(max_length=34)),
                ('hand', models.CharField(choices=[('CS', 'CS'), ('Extra', 'EXTRA'), ('PY', 'PY')], max_length=34)),
                ('annee_inscr', models.DateField(auto_now_add=True)),
                ('parent', models.CharField(max_length=34)),
                ('tel_parent', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causal', models.CharField(choices=[('insc', 'inscription'), ('sco', 'scolarite'), ('ten', 'tenue'), ('can', 'cantine')], max_length=34)),
                ('montant', models.CharField(max_length=34)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('note_Paiement', models.CharField(blank=True, max_length=200)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=34)),
                ('ordre_classe', models.CharField(max_length=4)),
                ('type_ecole', models.CharField(choices=[('MATERNELLE', 'CONF'), ('PRIMAIRE', 'ABAN'), ('PROP', 'PROP')], max_length=14)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve')),
            ],
        ),
    ]
