# Generated by Django 4.2.11 on 2024-04-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'Eleve', 'verbose_name_plural': 'Eleves'},
        ),
    ]
