# Generated by Django 4.2.11 on 2024-04-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_alter_eleve_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='paiment_set',
        ),
    ]
