# Generated by Django 4.2.11 on 2024-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_alter_eleve_cs_py_alter_eleve_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='type_ecole',
            field=models.CharField(choices=[('MATERNELLE', 'MATERNELLE'), ('PRIMAIRE', 'PRIMAIRE')], max_length=14),
        ),
    ]
