# Generated by Django 4.2.11 on 2024-04-21 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_alter_eleve_paiment_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='paiment_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scuelo.paiement'),
        ),
    ]
