# Generated by Django 4.2.11 on 2024-04-21 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_alter_eleve_paiment_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='paiment_set',
        ),
        migrations.AddField(
            model_name='paiement',
            name='eleve_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve'),
        ),
    ]
