# Generated by Django 4.2.11 on 2024-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_alter_classe_type_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom_classe',
            field=models.CharField(choices=[('PS', 'PS'), ('MS', 'MS'), ('GS', 'GS'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], max_length=34),
        ),
    ]
