# Generated by Django 4.2.11 on 2024-04-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_remove_eleve_paiment_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='paiment_set',
            field=models.ForeignKey(default='am coming', on_delete=django.db.models.deletion.CASCADE, to='scuelo.paiement'),
        ),
    ]
