# Generated by Django 4.2.11 on 2024-04-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0004_remove_eleve_paiment_set_paiement_eleve_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(),
        ),
    ]
