# Generated by Django 4.2.11 on 2024-04-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0005_alter_paiement_date_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterField(
            model_name='eleve',
            name='annee_inscr',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='condition_eleve',
            field=models.CharField(choices=[('CONF', 'CONF'), ('ABAN', 'ABAN'), ('PROP', 'PROP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='cs_py',
            field=models.CharField(choices=[('CS', 'CS'), ('Extra', 'EXTRA'), ('PY', 'PY')], max_length=6),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='hand',
            field=models.CharField(choices=[('DA', 'DA'), ('DM', 'DM'), ('DL', 'DL'), ('DV', 'DV')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_classe',
            field=models.CharField(choices=[('PS', 'PS'), ('MS', 'MS'), ('GS', 'GS'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], max_length=4),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='note_eleve',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sex',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='tel_parent',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='type_ecole',
            field=models.CharField(choices=[('MATERNELLE', 'MATERNELLE'), ('PRIMAIRE', 'PRIMAIRE')], max_length=14),
        ),
    ]
